### ISSUE TITLE
Effective date module not found when using bean-query

### ISSUE THREAD

**Issue by aleyoscar** [redstreet/beancount_reds_plugins#30]
Hello, I am using your `effective_date` plugin but am getting a `ModuleNotFoundError` when I try to run a query on a ledger using `bean-query`.

For example, when testing your `example.beancount` file located [here](https://github.com/redstreet/beancount_reds_plugins/blob/main/beancount_reds_plugins/effective_date/examples.beancount) I run `bean-check`, which passes, so then I try a simple query:

```
bean-query example.beancount "SELECT account, SUM(position) WHERE year=2013 GROUP BY account"
```

which fails with the following error:

```
<load>:0:       Error importing "beancount_reds_plugins.effective_date.effective_date": Traceback (most recent call last):
    File "/home/user/.local/share/pipx/venvs/beanquery/lib/python3.12/site-packages/beancount/loader.py", line 647, in run_transformations
      module = importlib.import_module(plugin_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'beancount_reds_plugins'
```

I used `pipx` to install your plugin, beancount, and beanquery.

beancount: 3.0.0
beanquery: 0.1.dev0
beancount-red-plugins: 0.3.0

Any thoughts? Could this be an issue with the latest beanquery?

Thanks for the plugin by the way! It looks very promising for my use case.

**Comment by redstreet** [comment]
Hi there,
Glad it might be helpful!

This would likely be a configuration issue at your end. `beancount_reds_plugins` is a standard python package, and neither does anything special nor requires anything other than a regular environment. 

Run this from a python shell from the same environment you're running bean-query from:

```
 import beancount_reds_plugins.effective_date
```

It should load fine (no errors). I suspect it doesn't, and it'll tell you what the issue is.

**Comment by aleyoscar** [comment]
So using `pipx` to install the plugin was the wrong approach, I wasn't aware how exactly `pipx` worked but after reading into it I was not using it correctly.

I tried again in a separate virtual environment as opposed to using `pipx` and the import works as does `bean-query`. I will need to use beancount in this environment from now on to use the plugin. Thanks!
